Fixing import issue in python script task resource
Previously, resourceTaskPythonScriptRead was missing the following fields:
- command_arguments
- additional_packages
- python_binary
This caused the following error when performing an import:
```
error=
| ImportStateVerify attributes not equivalent. Difference is shown below. The - symbol indicates attributes missing after import.
|
| \u00a0\u00a0map[string]string{
| -\u00a0\t"additional_packages": "pyyaml",
| -\u00a0\t"command_arguments":   "example",
| -\u00a0\t"python_binary":       "/usr/bin/python3",
| \u00a0\u00a0}
test_step_number=2 test_working_directory=/tmp/plugintest2032062785 test_name=TestAccMorpheusPythonScriptTask_import
hpe_morpheus_task_python_script_test.go:268: Step 2/2 error running import: ImportStateVerify attributes not equivalent. Difference is shown below. The - symbol indicates attributes missing after import.
        map[string]string{
    - 	"additional_packages": "pyyaml",
    - 	"command_arguments":   "example",
    - 	"python_binary":       "/usr/bin/python3",
        }
--- FAIL: TestAccMorpheusPythonScriptTask_import (9.52s)
```
The required lines have been added to the function so that running an import no longer
returns a difference.