Adding provider_id back to network router resource
This is needed for common scenarios where provider_id is used to create
other resources that depend on the network router provider_id such as under
gateway.
```
 Error: Unsupported attribute
│
│   on hpegl_all.tf line 78, in resource "hpe_morpheus_network" "static_net":
│   78:   connected_gateway     = hpe_morpheus_network_router.tf_tier1.provider_id
│
│ This object has no argument, nested block, or exported attribute named "provider_id".
╵
╷
│ Error: Unsupported attribute
│
│   on hpegl_all.tf line 186, in resource "hpe_morpheus_load_balancer" "tf_lb":
│  186:     tier1_gateway = hpe_morpheus_network_router.tf_tier1.provider_id
│
│ This object has no argument, nested block, or exported attribute named "provider_id".
╵
╷

```