Fix os_type code read bug (#1043)
We were seeing a failure on import step of
`TestAccMorpheusOsTypeExampleOk`.


```
=== RUN   TestAccMorpheusOsTypeExampleOk
=== PAUSE TestAccMorpheusOsTypeExampleOk
=== CONT  TestAccMorpheusOsTypeExampleOk
    resource_test.go:101: Step 2/2 error running import: ImportStateVerify attributes not equivalent.
 Difference is shown below. The - symbol indicates attributes missing after import.

          map[string]string{
        -       "code": "os.type-2177636368963882626",
          }
--- FAIL: TestAccMorpheusOsTypeExampleOk (3.12s)
FAIL
FAIL    github.com/HPE/terraform-provider-hpe/morpheus/framework/resources/ostype       4.521s
FAIL
```

Code was using plan in read erroneously.

It should not use plan.

It should be read from the response like everything else as it is
present when you GET an OS type.